### ISSUE TITLE
Invalid Location, please try submitting your test request again.

### ISSUE THREAD

**Issue by starandtina** [bayandin/webpagetest-private#2]
Hi, I'm getting this error after I input the testing URL:

~~~
Invalid Location, please try submitting your test request again.
~~~

I found the Test Location is empty, do I missed something? Thanks in advance.

**Comment by bayandin** [comment]
Hi there,
Sorry, this repo a little abandoned and work on it still not finished.
Maybe you should check docs for webpagetest here or ask your question in official forum here.

Thanks and sorry.

**Comment by starandtina** [comment]
@bayandin thanks for your help.
